In [0]:
## DATA GENERATION
import numpy as np

def generateX(cls):
    '''
    Inputs:
        cls: class {0, 1, 2}
    Outputs:
        a sample from cls
    '''
    assert cls in [0,1,2]
    if cls==0:
        return np.random.normal(np.array([0,0]),100)
    elif cls==1:
        return np.random.normal(np.array([200,200]),100)
    elif cls==2:
        return np.random.normal(np.array([-200,200]),100)
    assert False

In [0]:
def generateXY(N):
    '''
    Inputs:
        N: no. of samples of each class
    '''
    Y = []
    X = []
    for cls in range(3):
        for i in range(N):
            y = cls
            x = generateX(y)
            x = x.T
            Y.append(y)
            X.append(x)
    X = np.concatenate(X, axis=0) 
    Y = np.array(Y).reshape(-1,1)
    print(X.shape)
    print(Y.shape)
    return X, Y

def generateXY(N):
    '''
    Inputs:
        N: no. of samples of each class
    '''
    Y = [0]*N + [1]*N + [2]*N   # a list of 0s and 1s as ground truth classes  
    X = [generateX(y) for y in Y]  # samples corresponding to the ground truth Y
    X = np.vstack(X)   # arrange samples in different rows
    Y = np.array(Y).reshape(-1,1)
    return X, Y

X_train, Y_train_int = generateXY(50)
Nx = X_train.shape[1]

In [0]:
import numpy as np
x = np.array([[1, 2], [2, 30], [5, 6]])

In [3]:
x.shape

(3, 2)

In [0]:
print(x.reshape(3, 2, 1))

[[[ 1]
  [ 2]]

 [[ 2]
  [30]]

 [[ 5]
  [ 6]]]


[[[ 1]
  [ 2]
  [ 2]
  [30]
  [ 5]
  [ 6]]]


In [0]:
def oneHot(y, Ny):
    '''
    Input:
        y: an int in {0, 1, 2}
        Ny: Number of classes, e.g., 3 here.
    Output:
        Y: a vector of Ny (=3) tuples
    '''
    Y = np.zeros(Ny)
    Y[y] = 1
    return Y
Ny = 3
Y_train = np.array([oneHot(y,Ny) for y in Y_train_int])

In [0]:
x=np.array([[[1,0], [1,0], [1,0]], [[2,1], [2,1], [2,1]]])

In [0]:
x_ = np.sum(x, axis=2)
print(x_)
np.sum(x_ ,axis=1)

[[1 1 1]
 [3 3 3]]


array([3, 9])

In [0]:
def findMeanStddev(X):
    '''
    Input:
        x:a matrix of size (no,of samples, dimension of each sample)
    output:
        mean:mean of samples in X (same size as X)
        stddev:element-wise std dev of sample in X (same size as X)
  '''
    mean = np.sum(X, axis=0)/x.shape[0]
    X1 = X-mean
    stddev = np.sqrt(np.sum(X1*X1, axis=0))/X.shape[0]
    return mean, stddev
    